language: erlang

otp_release:
  - 19.2

sudo: false

addons:
  apt:
    packages:
    - git

before_script:
  - set -e
  - git clone --depth 1 --branch cl-1.2.3 https://github.com/tonyrog/cl.git
  - export ERL_LIBS=`pwd`
  - export MAKEFLAGS=-j6

script:
  - make unix

#after_success:
#  - $ERL_TOP/bin/dialyzer --build_plt --apps erts kernel stdlib wx --statistics
#  - $ERL_TOP/bin/dialyzer -n -Wunknown -Wunmatched_returns --apps compiler erts kernel stdlib asn1 crypto dialyzer hipe parsetools public_key runtime_tools sasl tools --statistics
#  - $ERL_TOP/bin/dialyzer -n --apps common_test debugger edoc inets mnesia observer ssh ssl syntax_tools tools wx xmerl --statistics
#  - ./otp_build tests && make release_docs

#after_script:
#  - ./scripts/run-smoke-tests
